### ISSUE TITLE
What does "-" bin event mean?

### ISSUE THREAD

**Issue by vandesm** [chernolab/ASpli#3]
I have a lot of bins that are significantly different between samples but there is no assigned bin event? Is this still considered an AS event? Is the bin (exon for example) just present more in one sample than the other?

**Comment by estepi** [comment]
Hi! thanks for your post.

Bins tagged as "-" refer to those bins which a priori due to annotation we dont expect alternative splicing. If in your analysis you find some of those bins are differentially spliced, it does mean they are "novel" aslternative splicing events. 

We treat all bins as putative alternative splicing bins

You can find more details in sectiion 6.1.2 Splicing event assignmen in the vignette (http://bioconductor.org/packages/release/bioc/vignettes/ASpli/inst/doc/ASpli.pdf)

I will be happy to provide more details
